version: '3'
services:
  robotsimulation:
    build: .
    ports:
      - "5080:5080"
    environment:
      - RUN_PORT=5080
    volumes:
      - ./NodeSimServer:/app
      - ./NodeSimServer/logs:/app/logs
      - /app/node_modules